### ISSUE TITLE
No Helper.php in the src folder

### ISSUE THREAD

**Issue by faheemhameed** [iLexN/HKID-Check-Digit#3]
Hi Alex,

First of thanks a lot for this cute little program. Very useful.

FYI, I have installed this last night using 

composer require ilexn/hkid-check-digit

After having installed it, I can't see the src/Helper.php

I have to resort to the following code:

`      
        //---------//
        $p1 = 'A';
        $p2 = '033362';
        $p3 = '5';

        $c = new HkidCheckDigit();

        if ($c->checkHKIDFormat($p1,$p2,$p3) === true) {
            echo ('correct');
        } else {
            echo ('wrong');
        }`

Please help check everything is fine.

Many thanks,
Hameed

**Comment by iLexN** [comment]
OMG, i missing the First Issue come from the public. 

I think the you install the version is not 2.x , the helper class only added in v2

v2 require php >=7.1
